spring:
  datasource:
    url: jdbc:postgresql://localhost/warehouse
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    contexts: dev